# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $stopwatch: '@?debug.stopwatch'
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\HealthController:
        bind:
            # for any $logger argument, pass this specific service
            $geoIpCache: '@App\Cache\GeoIpCache'

    App\Service\CacheManagerFactory:
        class: Qubit\Bundle\UtilsBundle\Factory\CacheManagerFactory
        public: true
        arguments:
            - '%env(CACHE_TYPE)%'
            - '%env(CACHE_DSN)%'
#            - '@?debug.stopwatch'
#            - 'redis'
#            - 'redis://127.0.0.1:6379'

    App\Cache\GeoIpCache:
        factory:   'App\Service\CacheManagerFactory:cacheManager'
        arguments: ['app.geo_ip']

    App\Service\BlacklistService:
        class: App\Service\BlacklistService
        arguments:
            - '@monolog.logger.blacklist'

    App\Service\WhitelistService:
        class: App\Service\WhitelistService
        arguments:
            - '@monolog.logger.whitelist'

    App\Service\GeoIpService:
        class: App\Service\GeoIpService
        public: true
        arguments:
            - '@App\Cache\GeoIpCache'
            - '@monolog.logger.geo_ip'
            - '@cravler_max_mind_geo_ip.service.geo_ip_service'
            - '@App\Service\BlacklistService'
            - '@App\Service\WhitelistService'
